# Generated by Django 4.1.2 on 2022-10-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=10000, null=True, verbose_name='Descricao'),
        ),
    ]
